PRINT "Coast to PERIAPSIS".
UNTIL ETA:PERIAPSIS < 20 {
  PRINT "Time to Maneuver" + (ETA:PERIAPSIS - 20).
  WAIT 1.
}
SET headTo TO PROGRADE.
LOCK STEERING TO headTo.
WAIT 5.
Lock THROTTLE TO 0.5.
WAIT UNTIL APOAPSIS > 520000.
LOCK THROTTLE TO 0.
WAIT UNTIL ALTITUDE > 520000.
STAGE.
